services:
  server:
    image: whisperx-server
    container_name: WhisperXSever
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    env_file:
      - whisper.env
    ports:
      - "8000:8000"
    environment:
      - HF_HOME=/app/hf_home
    volumes:
      - ./hf_home:/app/hf_home
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              #device_ids: ['0', '1'] # Select a gpu, or
              count: all
              capabilities: [gpu]
