services:
  server:
    image: whisperx-server
    container_name: WhisperXServer
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: uvicorn main:app --host ${TRANSCRIBATION_API_HOST} --port ${TRANSCRIBATION_API_PORT}
    ports:
      - ${TRANSCRIBATION_API_PORT}:${TRANSCRIBATION_API_PORT}
    volumes:
      - ./models:/app/models
      - tempfiles:/app/tempfiles
    restart: always
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              # device_ids: ['0', '1']
              count: all
              capabilities: [gpu]
volumes:
  tempfiles:
